### ISSUE TITLE
Add a feed?

### ISSUE THREAD

**Issue by tfausak** [samtay/samtay.github.io#1]
I would like to be able to follow an Atom or RSS feed of your posts. Hakyll supports this out of the box: https://jaspervdj.be/hakyll/tutorials/05-snapshots-feeds.html

**Comment by samtay** [comment]
Whoops, for some reason I didn't get notified on this. Thanks for the tip, I'll probably add that tomorrow.

**Comment by samtay** [comment]
I don't know a lot about RSS. Is it enough for me to have an accessible `https://samtay.github.io/feed.xml` and a link element
```html
<link rel="alternate" type="application/rss+xml" title="Sam Tay's FP dabbles" href="./feed.xml">
```
in the HTML, or do I have to add one of those icons that links to the feed?

**Comment by samtay** [comment]
I just added a couple anchors in the footer anyway. Should be deployed soon. Feel free to reopen if there's anything amiss in the feeds.

**Comment by tfausak** [comment]
The `<link rel=alternate` was enough for me. Thanks for adding the feed an links!
